### ISSUE TITLE
Add video to mood surfing app

### ISSUE THREAD

**Issue by inbalns** [MD2Korg/mCerebrum-MoodSurfing#5]
Tim/Monowar
To the first page of surf the mood following the sentence: "this exercise can help you use guided imagery to manage stress", please add the following question: "are you currently experiencing any unpleasant emotions?" ; then allow the participant to select Yes or No; 

If the answer is 'Yes': the next page should include the sentence: "This brief video will guide you through an exercise that can help in dealing with the unpleasant emotions you are experiencing" ; allow the participant to initiate video by pressing on  a button on the screen. At the end of the video, a page should appear, asking the participant "do you think this exercise was useful in dealing with your unpleasant emotions?" allow the participant to select Yes/No; the following page should be the congratulation page: "Congratulations: you have finished this exercise. You can come back to this exercise and surf your mood whenever you experience negative emotions".

If the answer is 'No': the following pages should be the existing pages that currently follow the first page of surf the mood.  

Let me know if you need additional clarifications.

Thank you both!

Billie

**Comment by twhnat** [comment]
@monowar Lets discuss the implications of this request before making a decision

**Comment by twhnat** [comment]
Should be resolved in the latest release.
