### ISSUE TITLE
Exiting intervention apps causes error

### ISSUE THREAD

**Issue by kevinmoran805** [MD2Korg/mCerebrum-MoodSurfing#8]
Going into either MoodSurfing or ThoughtShakeup, then backing out using back button on the phone causes error message: “Unfortunately, EMA Scheduler has stopped.” This error occurs with both Moodsurfing and ThoughtShakeup apps.

**Comment by monowar** [comment]
@kevinmoran805  In new version of EMAScheduler App this problem is resolved.
